# Generated by Django 2.2.4 on 2020-01-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=400)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('virtual', models.BooleanField()),
            ],
        ),
    ]
